name = "casita-worker"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[vars]
# Add non-secret environment variables here.
# Secrets (e.g. NOTION_TOKEN) must be set via:
#   wrangler secret put NOTION_TOKEN
NOTION_TODOS_DB = "332332846c00806480fdfd6be9f5ffa0"
